// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_avgButton = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_avgButton, 100);
    lv_obj_set_height(ui_avgButton, 50);
    lv_obj_set_x(ui_avgButton, -6);
    lv_obj_set_y(ui_avgButton, 72);
    lv_obj_set_align(ui_avgButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_avgButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_avgButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_avgButton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -1);
    lv_obj_set_y(ui_Label1, 1);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "AVG");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensorLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_sensorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensorLabel, -7);
    lv_obj_set_y(ui_sensorLabel, -57);
    lv_obj_set_align(ui_sensorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sensorLabel, "");
    lv_obj_set_style_text_font(ui_sensorLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_avgSensor = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_avgSensor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_avgSensor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_avgSensor, -9);
    lv_obj_set_y(ui_avgSensor, -4);
    lv_obj_set_align(ui_avgSensor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_avgSensor, "AVG");

    lv_obj_add_event_cb(ui_avgButton, ui_event_avgButton, LV_EVENT_ALL, NULL);

}
